# Generated by Django 5.2 on 2025-04-06 15:04

from django.db import migrations

class Migration(migrations.Migration):
    # Update dependencies to reference existing migrations
    dependencies = [
        ('expenses', '0001_initial'),  # Use the initial migration as a dependency
    ]

    operations = [
        # No operations needed for a merge migration
    ]
