# Generated by Django 5.2 on 2025-04-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_group_created_by_group_admin_and_more'),
        ('expenses', '0004_merge_20250406_2034'),
    ]

    operations = [
    ]
